In [10]:
import pandas as pd
from copy import deepcopy

In [2]:
spacers=pd.read_csv("/Users/milessmith/workspace/merrycrispr/merrycrispr/data/scored_spacers.csv")

In [3]:
on_target_threshold=(70/100)
off_target_threshold=100
spacers_per_feature=6

In [4]:
spacers.head()

,Unnamed: 0,gene_name,feature_id,start,stop,strand,spacer,score,hash,offtarget_score,number_matching
0,0,PML,ENSG00000140464,73994686,73994716,+,GCCCTGAGCCGGCACCTCCCCTTTCGGACA,0.316063,2273848149162870664,100.0,1
1,0,PML,ENSG00000140464,73994697,73994727,+,GCACCTCCCCTTTCGGACAGCTCAAGGGAC,0.472080,5251915309045097405,100.0,1
2,0,PML,ENSG00000140464,73994698,73994728,+,CACCTCCCCTTTCGGACAGCTCAAGGGACT,0.586884,5797773873868003637,100.0,1
3,0,PML,ENSG00000140464,73994712,73994742,+,GACAGCTCAAGGGACTCAGCCAACTGGCTC,0.493562,-1134622095285696753,100.0,1
4,0,PML,ENSG00000140464,73994780,73994810,+,CTAAACCGAGAATCGAAACTAAGCTGGGGT,0.442002,-6377816250002101177,100.0,1

In [5]:
spacers[spacers['score'] > on_target_threshold].head()

,Unnamed: 0,gene_name,feature_id,start,stop,strand,spacer,score,hash,offtarget_score,number_matching
6,0,PML,ENSG00000140464,73994782,73994812,+,AAACCGAGAATCGAAACTAAGCTGGGGTCC,0.704827,-1735800815052771319,100.0,1
31,0,PML,ENSG00000140464,73994999,73995029,+,AGGCGGGAAGAGAGGGTCTAACGGAGGATT,0.704000,-3622478272765482845,100.0,1
44,0,PML,ENSG00000140464,73995118,73995148,+,GATAGAGTAGAAAAGAGGACACGGAGGAGT,0.721110,-2894089583955006584,100.0,1
63,0,PML,ENSG00000140464,73995267,73995297,+,CAGATGCAGGACTTCAGATTAGGGAGGATG,0.726136,4285259529322382629,100.0,1
176,0,PML,ENSG00000140464,73997819,73997849,+,GAGCTGGAGGGCCTGAATAAATGGGGGTAT,0.732802,-5001609217183197492,100.0,1

In [6]:
spacers.sort_values('score', ascending = False).head(n=5)

,Unnamed: 0,gene_name,feature_id,start,stop,strand,spacer,score,hash,offtarget_score,number_matching
5435,0,PML,ENSG00000140464,73994672,73994702,+,TACATCTCGAAGGAGAAAACACAGTGGACT,0.824320,602798686121771327,100.000000,1
948,0,PML,ENSG00000140464,74012997,74013027,+,CAAATGTTCATTAGGACAGCTCTGGGGTCA,0.788640,-6164428667820817079,100.000000,1
3685,0,PML,ENSG00000140464,73994672,73994702,+,GGGAACACTGTTCGAGAAGCCATGGGGTGG,0.787661,4923344222223635815,100.000000,1
834,0,PML,ENSG00000140464,74010759,74010789,+,TTGTACTCTATGGCAAGAACCCAGAGGTCC,0.784481,-5188186216463325248,100.000000,1
537,0,PML,ENSG00000140464,74006646,74006676,+,TTGCATTGCTAGAAGGAATACCTGAGGCTG,0.782676,-5991081679487451833,19.481536,4

In [7]:
spacers.nlargest(5, 'score')

,Unnamed: 0,gene_name,feature_id,start,stop,strand,spacer,score,hash,offtarget_score,number_matching
5435,0,PML,ENSG00000140464,73994672,73994702,+,TACATCTCGAAGGAGAAAACACAGTGGACT,0.824320,602798686121771327,100.000000,1
948,0,PML,ENSG00000140464,74012997,74013027,+,CAAATGTTCATTAGGACAGCTCTGGGGTCA,0.788640,-6164428667820817079,100.000000,1
3685,0,PML,ENSG00000140464,73994672,73994702,+,GGGAACACTGTTCGAGAAGCCATGGGGTGG,0.787661,4923344222223635815,100.000000,1
834,0,PML,ENSG00000140464,74010759,74010789,+,TTGTACTCTATGGCAAGAACCCAGAGGTCC,0.784481,-5188186216463325248,100.000000,1
537,0,PML,ENSG00000140464,74006646,74006676,+,TTGCATTGCTAGAAGGAATACCTGAGGCTG,0.782676,-5991081679487451833,19.481536,4

In [11]:
grouped = spacers.groupby('gene_name').apply(lambda x: x.nlargest(5,'score'))
grouped

                Unnamed: 0 gene_name       feature_id     start      stop  \
gene_name
PML       5435           0       PML  ENSG00000140464  73994672  73994702
          948            0       PML  ENSG00000140464  74012997  74013027
          3685           0       PML  ENSG00000140464  73994672  73994702
          834            0       PML  ENSG00000140464  74010759  74010789
          537            0       PML  ENSG00000140464  74006646  74006676

               strand                          spacer     score  \
gene_name
PML       5435      +  TACATCTCGAAGGAGAAAACACAGTGGACT  0.824320
          948       +  CAAATGTTCATTAGGACAGCTCTGGGGTCA  0.788640
          3685      +  GGGAACACTGTTCGAGAAGCCATGGGGTGG  0.787661
          834       +  TTGTACTCTATGGCAAGAACCCAGAGGTCC  0.784481
          537       +  TTGCATTGCTAGAAGGAATACCTGAGGCTG  0.782676

                               hash  offtarget_score  number_matching
gene_name
PML       5435   602798686121771327       100.000000                1
          948  -6164428667820817079       100.000000                1
          3685  4923344222223635815       100.000000                1
          834  -5188186216463325248       100.000000                1
          537  -5991081679487451833        19.481536                4

In [12]:
ungrouped = deepcopy(grouped)
ungrouped.reset_index(drop=True)

,Unnamed: 0,gene_name,feature_id,start,stop,strand,spacer,score,hash,offtarget_score,number_matching
0,0,PML,ENSG00000140464,73994672,73994702,+,TACATCTCGAAGGAGAAAACACAGTGGACT,0.824320,602798686121771327,100.000000,1
1,0,PML,ENSG00000140464,74012997,74013027,+,CAAATGTTCATTAGGACAGCTCTGGGGTCA,0.788640,-6164428667820817079,100.000000,1
2,0,PML,ENSG00000140464,73994672,73994702,+,GGGAACACTGTTCGAGAAGCCATGGGGTGG,0.787661,4923344222223635815,100.000000,1
3,0,PML,ENSG00000140464,74010759,74010789,+,TTGTACTCTATGGCAAGAACCCAGAGGTCC,0.784481,-5188186216463325248,100.000000,1
4,0,PML,ENSG00000140464,74006646,74006676,+,TTGCATTGCTAGAAGGAATACCTGAGGCTG,0.782676,-5991081679487451833,19.481536,4

In [13]:
ungrouped.to_csv("/Users/milessmith/workspace/merrycrispr/merrycrispr/data/knockout_library_spacers.csv")

In [14]:
grouped.keys()

Index(['Unnamed: 0', 'gene_name', 'feature_id', 'start', 'stop', 'strand',
       'spacer', 'score', 'hash', 'offtarget_score', 'number_matching'],
      dtype='object')